# Generated by Django 3.2.9 on 2023-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='images',
            field=models.ImageField(blank=True, upload_to='./../images'),
        ),
    ]
