# Generated by Django 3.2.9 on 2023-07-30 14:15

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_unit_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='images',
            field=models.ImageField(blank=True, upload_to=courses.models.upload_to_images),
        ),
    ]
