# Generated by Django 3.2.9 on 2023-08-19 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
