# Generated by Django 3.2.9 on 2023-08-19 19:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
